name:                monad-transformers
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/chandrakoduru/monad-transformers#readme
license:             BSD3
author:              Chandra Koduru
maintainer:          chandrakoduru@outlook.com
copyright:           '2017'
category:            Learning Haskell
ghc-options: -Wall -Werror -Wno-unused-matches -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-import-lists
extra-source-files:
- README.md

dependencies:
  - base
  - containers == 0.5.7.1

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - Transformers
    - SampleExpressions

executables:
  monad-transformers:
    source-dirs:  app
    main:         Main.hs
    dependencies: 
      - monad-transformers
      - optparse-applicative == 0.14.0.0
      - gitrev

tests:
    monad-transformers-test:
      source-dirs: test
      main: Driver.hs
      dependencies:
        - monad-transformers
        - hspec
        - QuickCheck
        - tasty
        - tasty-hspec
        - tasty-hunit
        - tasty-quickcheck
        - tasty-discover
